services:
  php:
    container_name: php-apache
    build: '.'
    restart: unless-stopped
    volumes:
      - ./project:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    container_name: my-mysql
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: gbg
      MYSQL_USER: gbg
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gbg-phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: my-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8081:80

volumes:
  dbdata:
  project:
